nexxtway/react-rainbow-firebase-auth

src/redux/actions/app/start-application.js

fix: error message is shown when link to other page

---

src/i18n/translations.json
src/redux/services/firebase/resolve-errors.js

feat: add translate to the firebase message

---

src/i18n/__test__/utils.spec.js
src/i18n/utils.js

fix: changed to return locale from browser

---

src/components/experiences/social-login/styles.css

fix: change styles responsive design in signin and signup

---

src/components/pages/auth/home/index.js
src/components/pages/auth/home/media-queries.css
src/components/pages/auth/home/styles.css
src/components/pages/auth/profile/index.js
src/components/pages/auth/profile/media-queries.css
src/components/pages/auth/profile/styles.css
src/components/pages/auth/top-bar/index.js
src/components/pages/auth/top-bar/styles.css
src/components/pages/public/sign-in/media-queries.css
src/components/pages/public/sign-up/media-queries.css

fix: change responsive design in userProfile page

---

src/components/pages/auth/profile/__test__/isChangedValue.spec.js
src/components/pages/auth/profile/index.js
src/components/pages/auth/profile/isChangedValue.js
src/components/pages/auth/profile/profileActions.js

fix: fix render bottom bar in user profile page

---

src/components/pages/auth/profile/index.js
src/components/pages/auth/top-bar/index.js
src/components/pages/auth/top-bar/styles.css
src/components/pages/public/sign-up/index.js
src/redux/actions/authentication/__test__/facebook-login.spec.js
src/redux/actions/authentication/__test__/google-login.spec.js
src/redux/actions/authentication/google-login.js
src/redux/actions/registration/index.js
src/redux/actions/registration/reset.js
src/redux/reducers/app/index.js
src/redux/reducers/authentication/index.js
src/redux/reducers/authentication/user-getters.js
src/redux/reducers/forgotPassword/index.js
src/redux/reducers/profile/index.js
src/redux/reducers/registration/index.js
src/redux/services/firebase/google-sign-in.js

fix: fix render email in profile page and avatar

---

src/components/pages/auth/top-bar/styles.css

fix: fix z-index of the elements in userProfile.

---

src/components/pages/auth/home/media-queries.css
src/components/pages/auth/top-bar/styles.css

style: fix the home styles to mobile.

---

src/components/icons/person/index.js
src/components/pages/auth/profile/index.js
src/components/pages/auth/profile/styles.css

fix: profile user photo icon size

---

src/components/experiences/social-login/index.js

fix: translate select labels

---

src/components/experiences/message/index.js
src/components/experiences/message/styles.css
src/redux/reducers/app/index.js

style: add transition to message

---

src/redux/services/firebase/__test__/email-password-sign-in.spec.js
src/redux/services/firebase/__test__/facebook-sign-in.spec.js
src/redux/services/firebase/__test__/google-sign-in.spec.js
src/redux/services/firebase/__test__/sign-out-user.spec.js

test: add tests to services

---

package.json
yarn.lock

chore: remove the AWS packages

---

package.json
src/components/experiences/auth-route/index.js
src/components/experiences/public-route/index.js
src/redux/services/firebase/__test__/reauthenticate-user.spec.js
src/redux/services/firebase/reauthenticate-user.js
yarn.lock

chore: update firebase and firebase-tools

---

package.json
yarn.lock

chore: update redux version

---

package.json
yarn.lock

chore: update react-rainbow-components version

---

.stylelintrc.json
package.json
yarn.lock

chore: install styled-components

---

package.json
tsconfig.json
yarn.lock

chore: install Typescript first commit

---

.circleci/config.yml
.eslintrc.json
.gitignore
cypress.json
cypress/fixtures/example.json
cypress/integration/authentication/login.spec.js
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
package.json
src/components/pages/public/forgot-password/index.js
src/components/pages/public/forgot-password/media-queries.css
src/components/pages/public/privacy-policy/styles.css
src/components/pages/public/sign-in/index.js
src/components/pages/public/sign-in/media-queries.css
src/components/pages/public/sign-up/media-queries.css
src/components/pages/public/terms-condition/styles.css
yarn.lock

chore: cypress setup

---

README.md

docs: create a readme with the project info
